/*
 * Generated by ISE 13.11.9.3542 GPL Edition - windows
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F217_6147();
extern void F219_6298();
extern void F224_6367();
extern void F225_6505();
extern void F249_3479();
extern void F241_6031();
extern void F51_1182();
extern EIF_REFERENCE F51_1169();
extern EIF_BOOLEAN F51_1181();
extern EIF_BOOLEAN F51_1186();
extern void F51_1191();
extern void F51_1192();
extern void F51_1193();
extern void F44_1096();
extern EIF_TYPED_VALUE F44_1097();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F217_6147;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F224_6367;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F249_3479;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F219_6298;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F225_6505;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F241_6031;
#ifdef RTS_SCP_CAPABLE
	egc_is_scoop_capable = 0;
#endif
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F51_1182;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F51_1181;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F51_1169;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F51_1186;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F51_1191;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F51_1192;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F51_1193;

	egc_str_dtype = 218;

	egc_str32_dtype = 224;
	egc_arr_dtype = 248;
	egc_tup_dtype = 172;
	egc_disp_rout_id = 2642;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = (EIF_TYPE_INDEX)590;
	egc_sp_wchar = (EIF_TYPE_INDEX)783;
	egc_sp_bool = (EIF_TYPE_INDEX)393;
	egc_sp_uint8 = (EIF_TYPE_INDEX)705;
	egc_sp_uint16 = (EIF_TYPE_INDEX)672;
	egc_sp_uint32 = (EIF_TYPE_INDEX)425;
	egc_sp_uint64 = (EIF_TYPE_INDEX)438;
	egc_sp_int8 = (EIF_TYPE_INDEX)555;
	egc_sp_int16 = (EIF_TYPE_INDEX)746;
	egc_sp_int32 = (EIF_TYPE_INDEX)294;
	egc_sp_int64 = (EIF_TYPE_INDEX)468;
	egc_sp_real32 = (EIF_TYPE_INDEX)612;
	egc_sp_real64 = (EIF_TYPE_INDEX)328;
	egc_sp_pointer = (EIF_TYPE_INDEX)498;
	egc_sp_ref = (EIF_TYPE_INDEX)241;

	egc_uint8_ref_dtype = 194;
	egc_uint16_ref_dtype = 200;
	egc_uint32_ref_dtype = 197;
	egc_uint64_ref_dtype = 209;
	egc_int8_ref_dtype = 173;
	egc_int16_ref_dtype = 206;
	egc_int32_ref_dtype = 203;
	egc_int64_ref_dtype = 185;
	egc_bool_ref_dtype = 188;
	egc_real32_ref_dtype = 176;
	egc_char_ref_dtype = 182;
	egc_wchar_ref_dtype = 179;
	egc_real64_ref_dtype = 191;
	egc_point_ref_dtype = 212;

	egc_uint8_dtype = 195;
	egc_uint16_dtype = 201;
	egc_uint32_dtype = 198;
	egc_uint64_dtype = 210;
	egc_int8_dtype = 174;
	egc_int16_dtype = 207;
	egc_int32_dtype = 204;
	egc_int64_dtype = 186;
	egc_bool_dtype = 189;
	egc_real32_dtype = 177;
	egc_char_dtype = 183;
	egc_wchar_dtype = 180;
	egc_real64_dtype = 192;
	egc_point_dtype = 213;
#ifdef RTS_SCP_CAPABLE
#if RTS_SCP_CAPABLE == 1
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#else
	egc_scp_mngr_dtype = (EIF_TYPE_INDEX)0 - 1;
#endif
#endif

	egc_exception_dtype = 62;
	egc_except_emnger_dtype = 50;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;

	egc_fcall = egc_fcall_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "jeux";
	egc_system_location = "C:\\Users\\Utilisateur\\Documents\\Eiffel User Files\\13.11\\projects\\Jeux\\Kortal_Mombat\\Jeux\\EIFGENs\\jeux\\W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1392247727;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 862;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcorigin = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcoffset = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "GAME.make";
	egc_rcdt[0] = 0;
	egc_rcorigin[0] = 340;
	egc_rcoffset[0] = 0;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 43;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F44_1096;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F44_1097;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 858; /* GAME */
	}
}

#ifdef __cplusplus
}
#endif
